"""Build errors and in-place output writing (spec/build-pipeline.md)."""

import json
import os
import shutil

import pytest
from conftest import init_site, run_tada, set_site_config


def test_every_page_error_is_printed_once_with_a_project_relative_path(tmp_path):
    site = init_site(tmp_path)
    for name in ('one.md', 'two.md'):
        (site / 'content' / name).write_text(
            '---\ntitle: Broken\n---\n\n[missing](/missing.html)\n'
        )

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 1
    for name in ('one.md', 'two.md'):
        line = f'content/{name}: broken internal link'
        assert result.stdout.count(line) == 1
    assert str(site) not in result.stdout
    assert 'broken internal link' not in result.stderr
    assert 'tada dev failed: 2 errors' in result.stderr


def test_source_conflicting_with_a_generated_file_stops_the_build(tmp_path):
    site = init_site(tmp_path)
    set_site_config(site, {'features': {'favicon': True}})
    (site / 'public' / 'manifest.json').write_text('{}')

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 1
    assert 'public/manifest.json: conflicts with manifest.json generated by Tada' in result.stdout


def test_source_in_the_search_index_directory_stops_the_build(tmp_path):
    site = init_site(tmp_path)
    (site / 'public' / 'pagefind').mkdir()
    (site / 'public' / 'pagefind' / 'pagefind.js').write_text('')

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 1
    assert 'public/pagefind/pagefind.js: conflicts with the search index in pagefind/' in (
        result.stdout
    )


def test_dev_build_updates_dist_in_place(tmp_path):
    site = init_site(tmp_path)
    assert run_tada('dev', cwd=str(site)).returncode == 0
    dist = site / 'dist'
    dist_inode = dist.stat().st_ino
    (dist / 'stale.html').write_text('left over')
    (dist / 'old' / 'nested').mkdir(parents=True)
    (dist / 'old' / 'nested' / 'page.html').write_text('left over')
    search_files = sorted(p.name for p in (dist / 'pagefind').iterdir())

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 0, result.stdout + result.stderr
    assert dist.stat().st_ino == dist_inode
    assert not (dist / 'stale.html').exists()
    assert not (dist / 'old').exists()
    assert (dist / 'index.html').is_file()
    assert set(search_files) <= {p.name for p in (dist / 'pagefind').iterdir()}
    assert not list(tmp_path.glob('**/dist-*'))


def test_prod_version_without_a_manifest_is_ignored_and_replaced(tmp_path):
    site = init_site(tmp_path)
    assert run_tada('prod', cwd=str(site)).returncode == 0
    prod = site / 'dist-prod'
    leftover = prod / 'v2'
    leftover.mkdir()
    (leftover / 'partial.html').write_text('from a failed build')

    diff = run_tada('diff', cwd=str(site))
    assert diff.returncode == 1
    assert 'at least two' in diff.stderr

    result = run_tada('prod', cwd=str(site))

    assert result.returncode == 0, result.stdout + result.stderr
    assert not (leftover / 'partial.html').exists()
    manifest = json.loads((leftover / 'tada.manifest.json').read_text())
    assert manifest['build'] == 2
    assert (leftover / 'index.html').is_file()


def test_output_that_is_both_a_file_and_a_directory_stops_the_build(tmp_path):
    site = init_site(tmp_path)
    (site / 'public' / 'foo').write_text('a file')
    (site / 'content' / 'foo').mkdir()
    (site / 'content' / 'foo' / 'bar.png').write_bytes(b'png')

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 1
    assert result.stdout.count('foo is both a file and a directory') == 1
    assert 'content/foo/bar.png, public/foo' in result.stdout
    assert not (site / 'dist').exists()


def test_source_named_like_the_search_index_directory_stops_the_build(tmp_path):
    site = init_site(tmp_path)
    (site / 'public' / 'pagefind').write_text('a file')

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 1
    assert 'public/pagefind: conflicts with the search index in pagefind/' in result.stdout


def test_full_build_replaces_a_stale_empty_directory(tmp_path):
    site = init_site(tmp_path)
    (site / 'dist' / 'about.html' / 'empty').mkdir(parents=True)
    (site / 'content' / 'about.md').write_text('---\ntitle: About\n---\n\nAbout.\n')

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 0, result.stdout + result.stderr
    assert (site / 'dist' / 'about.html').is_file()


def test_malformed_front_matter_is_reported_for_every_page(tmp_path):
    site = init_site(tmp_path)
    for name in ('one.md', 'two.md'):
        (site / 'content' / name).write_text('---\ntitle: Unclosed\n\nBody\n')

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 1
    for name in ('one.md', 'two.md'):
        assert result.stdout.count(f'content/{name}: ') == 1
    assert 'tada dev failed: 2 errors' in result.stderr


def test_full_build_never_deletes_through_a_symlinked_directory(tmp_path):
    site = init_site(tmp_path)
    assert run_tada('dev', cwd=str(site)).returncode == 0
    outside = tmp_path / 'outside'
    (outside / 'sub').mkdir(parents=True)
    precious = outside / 'sub' / 'precious.txt'
    precious.write_text('keep me')
    link = site / 'dist' / 'media'
    try:
        os.symlink(outside, link, target_is_directory=True)
    except OSError:
        pytest.skip('symlinks are not permitted here')

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 0, result.stdout + result.stderr
    assert precious.read_text() == 'keep me'
    assert not link.exists() and not link.is_symlink()


def test_full_build_never_writes_through_a_symlinked_output_file(tmp_path):
    site = init_site(tmp_path)
    assert run_tada('dev', cwd=str(site)).returncode == 0
    outside = tmp_path / 'outside.html'
    outside.write_text('keep me')
    index = site / 'dist' / 'index.html'
    index.unlink()
    try:
        os.symlink(outside, index)
    except OSError:
        pytest.skip('symlinks are not permitted here')

    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 0, result.stdout + result.stderr
    assert outside.read_text() == 'keep me'
    assert index.is_file() and not index.is_symlink()


def test_rebuilt_search_index_has_no_stale_files(tmp_path):
    site = init_site(tmp_path)
    index_md = site / 'content' / 'index.md'
    search_dir = site / 'dist' / 'pagefind'

    def search_files():
        return sorted(p.relative_to(search_dir) for p in search_dir.rglob('*') if p.is_file())

    assert run_tada('dev', cwd=str(site)).returncode == 0
    index_md.write_text(index_md.read_text() + '\n\nA new paragraph about zebras.\n')
    assert run_tada('dev', cwd=str(site)).returncode == 0
    rebuilt = search_files()

    shutil.rmtree(site / 'dist')
    assert run_tada('dev', cwd=str(site)).returncode == 0
    assert rebuilt == search_files()


def test_search_index_replaces_a_stale_pagefind_file(tmp_path):
    site = init_site(tmp_path)
    set_site_config(site, {'features': {'search': False}})
    (site / 'public' / 'pagefind').write_text('a file')
    assert run_tada('dev', cwd=str(site)).returncode == 0
    assert (site / 'dist' / 'pagefind').is_file()

    (site / 'public' / 'pagefind').unlink()
    set_site_config(site, {'features': {'search': True}})
    result = run_tada('dev', cwd=str(site))

    assert result.returncode == 0, result.stdout + result.stderr
    assert (site / 'dist' / 'pagefind').is_dir()
