import pytest

from conftest import run_tada


class TestLiterateJavaPages:
    """Literate Java pages should be rendered with .java.html extension."""

    @pytest.fixture
    def site_dir(self, tmp_path):
        result = run_tada("init", "testsite", "--no-interactive", cwd=str(tmp_path))
        assert result.returncode == 0, f"init failed: {result.stderr}"
        yield tmp_path / "testsite"

    @pytest.fixture
    def built_site(self, site_dir):
        result = run_tada("dev", cwd=str(site_dir))
        assert result.returncode == 0, f"dev build failed: {result.stderr}"
        yield site_dir

    def test_literate_java_page_has_java_html_extension(self, built_site):
        """Pair.java.md should produce Pair.java.html and Pair.java."""
        dist = built_site / "dist"
        # Pair.java.md is a literate Java page in the example site
        java_html = dist / "lectures" / "01" / "Pair.java.html"
        assert java_html.exists(), f"Expected Pair.java.html to exist at {java_html}"

        # The literate Java page should always produce a .java file
        code_file = dist / "lectures" / "01" / "Pair.java"
        assert code_file.exists(), f"Expected Pair.java to exist at {code_file}"


class TestLiterateJavaLinkNotRewritten:
    """When features.code is true, links to .java files generated by literate
    Java pages should not be rewritten to .java.html."""

    @pytest.fixture
    def site_dir(self, tmp_path):
        result = run_tada("init", "testsite", "--no-interactive", cwd=str(tmp_path))
        assert result.returncode == 0, f"init failed: {result.stderr}"
        site = tmp_path / "testsite"

        content = site / "content" / "test"
        content.mkdir(parents=True)

        # A literate Java file
        (content / "Hello.java.md").write_text(
            "---\ntitle: Hello\n---\n\n"
            "```java\n"
            "public class Hello {\n"
            "    public static void main(String[] args) {\n"
            '        System.out.println("hi");\n'
            "    }\n"
            "}\n"
            "```\n"
        )

        # A regular code file
        (content / "Plain.java").write_text(
            "public class Plain {}\n"
        )

        # A page that links to both
        (content / "index.md").write_text(
            "---\ntitle: Test\n---\n\n"
            "* [Hello source](./Hello.java)\n"
            "* [Plain source](./Plain.java)\n"
        )

        yield site

    @pytest.fixture
    def built_site(self, site_dir):
        result = run_tada("dev", cwd=str(site_dir))
        assert result.returncode == 0, f"dev build failed: {result.stderr}"
        yield site_dir

    def test_literate_java_link_not_rewritten(self, built_site):
        """Link to Hello.java (literate Java output) should stay as .java."""
        html = (built_site / "dist" / "test" / "index.html").read_text()
        assert 'href="./Hello.java"' in html
        assert 'href="./Hello.java.html"' not in html

    def test_code_page_link_still_rewritten(self, built_site):
        """Link to Plain.java (a code page) should be rewritten to .java.html."""
        html = (built_site / "dist" / "test" / "index.html").read_text()
        assert 'href="./Plain.java.html"' in html


class TestLiterateJavaBrokenLink:
    """A literate Java page with a broken internal link should fail the build."""

    @pytest.fixture
    def site_dir(self, tmp_path):
        result = run_tada("init", "testsite", "--no-interactive", cwd=str(tmp_path))
        assert result.returncode == 0, f"init failed: {result.stderr}"
        site = tmp_path / "testsite"

        content = site / "content" / "test"
        content.mkdir(parents=True)

        (content / "Broken.java.md").write_text(
            "---\ntitle: Broken\n---\n\n"
            "See [this page](./nonexistent.html).\n\n"
            "```java\n"
            "public class Broken {}\n"
            "```\n"
        )

        yield site

    def test_build_fails(self, site_dir):
        result = run_tada("dev", cwd=str(site_dir))
        assert result.returncode != 0
        output = result.stdout + result.stderr
        assert "broken internal link" in output
