import json
import os
import re
import subprocess

import pytest
from conftest import (
    PACKAGE_DIR,
    SITE_DEV_CONFIG_FILE,
    init_site,
    load_structured_file,
    make_fake_failing_command,
    parse_head_metadata,
    run_tada,
    set_site_config,
    straight_quotes,
)


def _write_basic_literate_java_site(site):
    lectures_dir = site / 'content' / 'lectures' / '01'
    lectures_dir.mkdir(parents=True, exist_ok=True)
    (site / 'content' / 'lectures' / 'index.md').write_text(
        '---\ntitle: Lectures\n---\n\n[Lecture 1](./01/index.html)\n'
    )
    (lectures_dir / 'index.md').write_text(
        '---\ntitle: Lecture 1\n---\n\n[Pair source](./Pair.java)\n'
    )
    (lectures_dir / 'Pair.java.md').write_text(
        '---\ntitle: Pair\n---\n\n'
        '```java\n'
        'public class Pair {\n'
        '  public static void main(String[] args) {\n'
        '    System.out.println("pair");\n'
        '  }\n'
        '}\n'
        '```\n'
    )


class TestLiterateJavaPages:
    """Literate Java pages should be rendered with .java.html extension."""

    @pytest.fixture
    def site_dir(self, tmp_path):
        site = init_site(tmp_path, bare=True)
        _write_basic_literate_java_site(site)
        yield site

    def test_literate_java_page_has_java_html_extension(self, built_dev_site):
        """Pair.java.md should produce Pair.java.html and Pair.java."""
        dist = built_dev_site / 'dist'
        java_html = dist / 'lectures' / '01' / 'Pair.java.html'
        assert java_html.exists(), f'Expected Pair.java.html to exist at {java_html}'

        # The literate Java page should always produce a .java file
        code_file = dist / 'lectures' / '01' / 'Pair.java'
        assert code_file.exists(), f'Expected Pair.java to exist at {code_file}'


class TestLiterateJavaLinkNotRewritten:
    """Links to .java files generated by literate
    Java pages should not be rewritten to .java.html."""

    @pytest.fixture
    def site_dir(self, tmp_path):
        site = init_site(tmp_path, bare=True)
        set_site_config(site, {'extensionToShikiLanguage': {'java': 'java'}})

        content = site / 'content' / 'test'
        content.mkdir(parents=True)

        # A literate Java file
        (content / 'Hello.java.md').write_text(
            '---\ntitle: Hello\n---\n\n'
            '```java\n'
            'public class Hello {\n'
            '    public static void main(String[] args) {\n'
            '        System.out.println("hi");\n'
            '    }\n'
            '}\n'
            '```\n'
        )

        # A regular code file
        (content / 'Plain.java').write_text('public class Plain {}\n')

        # A page that links to both
        (content / 'index.md').write_text(
            '---\ntitle: Test\n---\n\n'
            '* [Hello source](./Hello.java)\n'
            '* [Plain source](./Plain.java)\n'
        )

        yield site

    def test_literate_java_link_not_rewritten(self, built_dev_site):
        """Link to Hello.java (literate Java output) should stay as .java."""
        html = (built_dev_site / 'dist' / 'test' / 'index.html').read_text()
        assert 'href="./Hello.java"' in html
        assert 'href="./Hello.java.html"' not in html

    def test_code_page_link_still_rewritten(self, built_dev_site):
        """Link to Plain.java (a code page) should be rewritten to .java.html."""
        html = (built_dev_site / 'dist' / 'test' / 'index.html').read_text()
        assert 'href="./Plain.java.html"' in html


class TestLiterateJavaBrokenLink:
    """A literate Java page with a broken internal link should fail the build."""

    @pytest.fixture
    def site_dir(self, tmp_path):
        site = init_site(tmp_path, bare=True)

        content = site / 'content' / 'test'
        content.mkdir(parents=True)

        (content / 'Broken.java.md').write_text(
            '---\ntitle: Broken\n---\n\n'
            'See [this page](./nonexistent.html).\n\n'
            '```java\n'
            'public class Broken {}\n'
            '```\n'
        )

        yield site

    def test_build_fails(self, site_dir):
        result = run_tada('dev', cwd=str(site_dir))
        assert result.returncode != 0
        output = result.stdout + result.stderr
        assert 'broken internal link' in output


def _write_literate_page(site, front_matter):
    (site / 'content' / 'Pair.java.md').write_text(
        f'---\n{front_matter}---\n\n```java\npublic class Pair {{}}\n```\n'
    )


def _env_without_javac(tmp_path):
    fake_dir = tmp_path / 'fake_bin'
    fake_dir.mkdir()
    make_fake_failing_command(fake_dir, 'javac')
    return {**os.environ, 'PATH': str(fake_dir) + os.pathsep + os.environ.get('PATH', '')}


class TestLiterateJavaFrontMatter:
    """Literate Java pages prepare front matter the same way as other pages."""

    def test_broken_parent_fails_build(self, site_dir):
        _write_literate_page(site_dir, 'title: Pair\nparent: /does-not-exist.html\n')
        result = run_tada('dev', cwd=str(site_dir))
        assert result.returncode != 0
        assert 'Pair.java.md: broken parent link: "/does-not-exist.html"' in (
            result.stdout + result.stderr
        )

    def test_broken_parent_fails_build_without_javac(self, site_dir, tmp_path):
        _write_literate_page(site_dir, 'title: Pair\nparent: /does-not-exist.html\n')
        result = run_tada('dev', cwd=str(site_dir), env=_env_without_javac(tmp_path))
        output = result.stdout + result.stderr
        assert 'javac was not found' in output
        assert result.returncode != 0
        assert 'Pair.java.md: broken parent link: "/does-not-exist.html"' in output

    def test_valid_parent_renders_breadcrumb(self, site_dir):
        _write_literate_page(site_dir, 'title: Pair\nparent: ./index.html\nparentLabel: Home\n')
        result = run_tada('dev', cwd=str(site_dir))
        assert result.returncode == 0, result.stdout + result.stderr
        html = (site_dir / 'dist' / 'Pair.java.html').read_text()
        breadcrumb = re.search(r'<a\b([^>]*\bclass="breadcrumb"[^>]*)>([^<]*)</a>', html)
        assert breadcrumb, 'missing breadcrumb link'
        assert 'href="./index.html"' in breadcrumb[1]
        assert breadcrumb[2] == 'Home'

    def test_description_with_quotes_produces_valid_meta(self, site_dir):
        _write_literate_page(site_dir, 'title: Pair\ndescription: She said "hi" to *Pair*\n')
        result = run_tada('dev', cwd=str(site_dir))
        assert result.returncode == 0, result.stdout + result.stderr
        head = parse_head_metadata((site_dir / 'dist' / 'Pair.java.html').read_text())
        assert straight_quotes(head.meta['description']) == 'She said "hi" to Pair'
        assert sorted(head.meta_attrs['description']) == ['content', 'name']

    def test_front_matter_templates_are_interpolated(self, site_dir):
        site_title = load_structured_file(site_dir / SITE_DEV_CONFIG_FILE)['title']
        _write_literate_page(
            site_dir,
            'title: <%= site.title %> Pair\ndescription: About <%= site.title %>\n',
        )
        result = run_tada('dev', cwd=str(site_dir))
        assert result.returncode == 0, result.stdout + result.stderr
        head = parse_head_metadata((site_dir / 'dist' / 'Pair.java.html').read_text())
        assert head.meta['og:title'] == f'{site_title} Pair'
        assert head.meta['description'] == f'About {site_title}'

    def test_slides_front_matter_fails_build(self, site_dir):
        _write_literate_page(site_dir, 'title: Pair\nslides: true\n')
        result = run_tada('dev', cwd=str(site_dir))
        assert result.returncode != 0
        assert 'Pair.java.md: slides mode is only supported on Markdown pages' in (
            result.stdout + result.stderr
        )


@pytest.mark.parametrize(
    'output',
    [
        ''.join(chr(code) for code in range(32)),
        'ordinary output: "quoted" and \\backslash\nnext line\rreturn\ttab',
    ],
    ids=['all-control-characters', 'ordinary-output'],
)
def test_literate_java_stdout_round_trip(tmp_path, output):
    """Execute real Java and preserve stdout through the runner JSON protocol."""
    # Numeric char literals also exercise NUL and controls that cannot occur in
    # Java source literals (Unicode escapes are processed before tokenization).
    chars = ', '.join(str(ord(char)) for char in output)
    source = (
        'public class Output {\n'
        '  public static void main(String[] args) {\n'
        f'    System.out.print(new String(new char[] {{{chars}}}));\n'
        '  }\n'
        '}\n'
    )
    module = PACKAGE_DIR / 'build' / 'utils' / 'literate-java.ts'
    script = tmp_path / 'execute.ts'
    script.write_text(
        f'import {{compileJavaSource, executeLiterateJava}} from {json.dumps(str(module))};\n'
        'import fs from "node:fs";\n'
        f'const dir = compileJavaSource({json.dumps(source)}, "Output");\n'
        'try {\n'
        '  const result = executeLiterateJava("Output", dir, '
        '[{javaStartLine: 3, javaEndLine: 3}] as any);\n'
        '  console.log(JSON.stringify(result));\n'
        '} finally { fs.rmSync(dir, {recursive: true, force: true}); }\n'
    )
    result = subprocess.run(['bun', str(script)], capture_output=True, text=True, timeout=60)
    assert result.returncode == 0, result.stdout + result.stderr
    assert json.loads(result.stdout) == [{'blockIndex': 0, 'output': output}]


def test_literate_java_partials_render_extract_and_watch(tmp_path):
    from watch_helpers import WatchProcess

    site = init_site(tmp_path, bare=True)
    content = site / 'content'
    (content / 'parts').mkdir()
    (content / 'Example.java.md').write_text(
        '---\ntitle: Included example\ntoc: true\n---\n\n{{{ parts/_outer.md }}}\n'
    )
    (content / 'parts' / '_outer.md').write_text('## <%= page.title %>\n\n{{{ _body.md }}}\n')
    partial = content / 'parts' / '_body.md'

    def write_partial(value):
        partial.write_text(
            f'Included prose {value}.\n\n'
            '<!---\n```java\npublic class Example {\n```\n-->\n\n'
            '```java\n'
            f'  public static int value = {value};\n'
            '```\n\n<!---\n```java\n}\n```\n-->\n'
        )

    write_partial(1)
    result = run_tada('dev', cwd=str(site))
    assert result.returncode == 0, result.stdout + result.stderr
    page = site / 'dist' / 'Example.java.html'
    source = site / 'dist' / 'Example.java'
    html = page.read_text()
    assert 'Included prose 1.' in html
    assert 'href="#included-example"' in html
    assert '{{{' not in html
    assert 'public class Example' not in html
    assert 'id="L2"' in html
    assert 'public static int value = 1;' in source.read_text()
    assert not (site / 'dist' / 'parts' / '_body.html').exists()

    wp = WatchProcess(site)
    try:
        wp.wait_for_initial_build()
        before = page.stat().st_mtime
        write_partial(2)
        wp.wait_for_rebuild(page, 'modified', before_mtime=before)
        assert 'Included prose 2.' in page.read_text()
        assert 'public static int value = 2;' in source.read_text()
    finally:
        wp.stop()
