name: Build and deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install -y mupdf-tools

    - name: Use Bun
      uses: oven-sh/setup-bun@v2

    - run: bun install

    - name: Unit tests
      run: bun test

    # If unit tests didn't fail, run the functional tests

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install pytest
      run: pip install pytest

    - name: Run functional tests
      run: bun run test:functional

    # Initialize & build the example site configured for GitHub Pages

    - name: Initialize example site
      run: >
        bun run bin/tada.ts init example --no-interactive
        --prod-base https://abreen.io
        --prod-base-path /Tada

    - name: Build example site
      run: ../bin/tada.ts prod
      working-directory: example

    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: example/dist/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  purge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything": true}'
