name: Build and deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install -y mupdf-tools jq

    - name: Use Bun
      uses: oven-sh/setup-bun@v2

    - run: bun install

    - name: Initialize example site
      run: bun run init-example

    - name: Modify config for GitHub Pages
      run: >
        jq '
        .base |= "https://abreen.io" |
        .basePath |= "/Tada" |
        .internalDomains |= ["abreen.io"]'
        site.prod.json > site.prod.json.new

        mv site.prod.json.new site.prod.json
      working-directory: example

    - name: Build example site
      run: bun run ../bin/tada.js prod
      working-directory: example

    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: example/dist/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
